# Generated by Django 5.2.14 on 2026-05-28 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requestscust', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('support', 'SUPPROT'), ('sales', 'SALES'), ('billing', 'BILLING')], max_length=20)),
                ('priority', models.CharField(choices=[('low', 'LOW'), ('medium', 'MEDIUM'), ('high', 'HIGH')], max_length=20)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='requestscust.customerrequest')),
            ],
        ),
    ]
